### ISSUE TITLE
[FAQ] - Add a new tip: Label in visualizations

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/docs#103]
### How can I add a label to my visualization?

You can add labels to your layers modifying you CartoCSS code. Also, you can modify text properties. 
Example:

{% highlight scss %}
#your_table_name {
   text-name: [your_field_name];
   text-face-name: 'DejaVu Sans Book';
   text-size: 10;
   text-label-position-tolerance: 10;
   text-fill: #000;
   text-halo-fill: #FFF;
   text-halo-radius: 1;
   text-dy: -10;
   text-allow-overlap: true;
   text-placement: point;
   text-placement-type: simple;
}
{% endhighlight %}

--------

What do you think @iriberri ? Do you want me to do a PR with this?

**Comment by csobier** [comment]
@iriberri Is this issue still applicable?  There is a Label text option available from the Wizard.  Or is this feature to describe how to customize label text?

**Comment by iriberri** [comment]
I'd close this. This applies for the label text option available in the wizard, and besides that, we don't have recurrent questions about this, so I think it's not worthy.

**Comment by csobier** [comment]
:+1:
