### ISSUE TITLE
remove this section from the FAQ

### ISSUE THREAD

**Issue by javisantana** [CartoDB/docs#131]
"How can I change the privacy of my tables without using the UI?"

the api is not documented and it is failing

**Comment by matallo** [comment]
bump

**Comment by javisantana** [comment]
the issues is that we are making public an API that is not public and that's a big problem for us while developing

**Comment by javisantana** [comment]
said that, if someone ask it, tell them how to do it and warn they that it could be changed any time but we can't not write anything like that in a public page

**Comment by iriberri** [comment]
Understood, I'm on it :smile:
