### ISSUE TITLE
Sort records by distance

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#133]
http://docs.cartodb.com/tips-and-tricks.html#sort-records-by-distance-to-a-point

Martin B. says:

In your docs on "Sort records by distance to a point" you are recommending ORDER BY the result of ST_Distance().
http://docs.cartodb.com/tips-and-tricks.html#sort-records-by-distance-to-a-point

You can instead use KNN indexing and the <-> operator, which offers better performance.
http://boundlessgeo.com/2011/09/indexed-nearest-neighbour-search-in-postgis/
Since you guys (Vizzuality) sponsored this development in PostGIS I’m surprised you aren’t promoting it!

Best regards,

What do you think, @andrewxhill ? :-) please, take a look at this: https://cartodb.supportbee.com/tickets/4104503

**Comment by csobier** [comment]
@andrewxhill or @iriberri , Can you verify the edits below?  I need to confirm some syntax details before updating in the doc.

**Here is the original code:**
```
DISTANCE SORT
SELECT ST_X(ST_Centroid(the_geom)) as longitude,ST_Y(ST_Centroid(the_geom)) as latitude, description, ST_Distance(the_geom::geography, ST_PointFromText('POINT(-73.999548 40.71954)', 4326)::geography) AS distance FROM {table_name} ORDER BY distance ASC LIMIT 10
```

**Here is the edited code and a note that I will add:** Based on Pramsey's example, please confirm:
- Should "geom" appear after ORDER BY clause and before the distance operator?
- Should a semi-colon be added after the LIMIT value?  
- Should LIMIT be on it's own line?
```
DISTANCE SORT
SELECT ST_X(ST_Centroid(the_geom)) as longitude,ST_Y(ST_Centroid(the_geom)) as latitude, description, ST_Distance(the_geom::geography, ST_PointFromText('POINT(-73.999548 40.71954)', 4326)::geography) AS distance FROM {table_name} ORDER BY geom <-> ASC LIMIT 10;
```
**Note:** The ORDER BY clause includes the `<->` distance operator as a PostGIS bounding box index. This operator only returns sorted index results when it is combined with the ORDER BY clause, and a defined LIMIT, drastically improving performance. For more details, see [Indexed Nearest Neighbour Search in PostGIS](http://boundlessgeo.com/2011/09/indexed-nearest-neighbour-search-in-postgis/).

**Comment by iriberri** [comment]
Nope, sorry. Notice that you're not comparing the_geom with anything in your syntax.

You'd need:

```sql
SELECT ST_X(ST_Centroid(the_geom)) as longitude,ST_Y(ST_Centroid(the_geom)) as latitude, description FROM ne_10m_populated_places_simple_18 ORDER BY the_geom <-> ST_PointFromText('POINT(-73.999548 40.71954)', 4326) LIMIT 10
```

Or, if you're not interested in showing the distance itself, you can discard it in the SELECT statement and just do:

```sql
SELECT ST_X(ST_Centroid(the_geom)) as longitude,ST_Y(ST_Centroid(the_geom)) as latitude, description, ST_Distance(the_geom::geography, ST_PointFromText('POINT(-73.999548 40.71954)', 4326)::geography) AS distance FROM ne_10m_populated_places_simple_18 ORDER BY the_geom <-> ST_PointFromText('POINT(-73.999548 40.71954)', 4326) LIMIT 10
```

Hope this helps.
