### ISSUE TITLE
Torque API docs no longer on the docs website

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#156]
Not sure when it got dropped..

https://github.com/CartoDB/torque/blob/master/doc/API.md

Likely we want the CartoCSS one too.

@matallo @saleiva

**Comment by javisantana** [comment]
hey, not sure if the doc was in docs website

**Comment by matallo** [comment]
it's never ever been there, +1 to add these docs

**Comment by pramsey** [comment]
Yes, finding the CartoCSS docs were only on MapBox was a bit odd. It's a core part of the product, odd to have to go to a "competitor" site for them.

**Comment by matallo** [comment]
in the meantime, we have the torque CartoCSS covered https://github.com/CartoDB/docs/pull/158, but yeah, will ping @brittanymicek to help here

**Comment by andrewxhill** [comment]
wait, this should be pulled in from cartodb/torque API.md right? this isn't something we need to rewrite. just like cartodb.js is pulled in automatically

**Comment by javisantana** [comment]
Cartocss doc should be generated from reference, @fdansv can point to the
needed repo.

A cartocss reference to html script can be done in 20 minutes

**Comment by matallo** [comment]
+1 to @andrewxhill 
+1 to @javisantana 

feel free to assign this to me, just not to the current sprint

**Comment by fdansv** [comment]
https://github.com/cartodb/torque-reference

**Comment by andrewxhill** [comment]
Next sprint? @saleiva

**Comment by andrewxhill** [comment]
nevermind, looks fixed. close?

**Comment by csobier** [comment]
@andrewxhill Is there still a doc requirement here?

**Comment by matallo** [comment]
two things here: cartocss (which is being covered in its own PR https://github.com/CartoDB/docs/pull/388)
and torque (that if I'm not wrong should be the content of https://github.com/CartoDB/torque/blob/master/doc/API.md)

we should have this for Torque landing page in the commercial website @csobier

**Comment by csobier** [comment]
@andrewxhill , I am reassigning this issue to the next milestone. Can you clarify what the documentation requirement is for the Docs site?  Should the github resource, mentioned above, be added to the SQL API doc?  Please advise.

**Comment by csobier** [comment]
ping

**Comment by andrewxhill** [comment]
oop, sorry! so here is the torque doc

https://github.com/CartoDB/torque/blob/master/doc/API.md

i don't think we should add all of it, because it is generic (for use outside of cartodb). however, som bits of it are particularly useful even inside of cartodb.js apps, e.g.

https://github.com/CartoDB/torque/blob/master/doc/API.md#interaction-methods-only-available-for-leaflet

**Comment by csobier** [comment]
Bumping to next milestone, as Andrew cannot review branch in progress until next week.
