### ISSUE TITLE
Include search bar/functionality on CartoDB docs page

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/docs#159]
No ability for users to search documentation.

**Comment by iriberri** [comment]
We've just been asked about this today in support. :+1:

**Comment by matallo** [comment]
yeah, it's a long-time request, but haven't been able to look into it yet

https://alexpearce.me/2012/04/simple-jekyll-searching/
https://github.com/blog/1939-how-github-uses-github-to-document-github

**Comment by csobier** [comment]
Dup #279
