### ISSUE TITLE
Add documentation section of oEmbed support

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#164]
We now have an oEmbed API endpoint
This should live in the Platform

We might need a new section. What do you think @javisantana? 

@michellechandra see the spec here,

http://oembed.com/

see it running live here,

http://services.cartodb.com/oembed?url=https://osm2.cartodb.com/viz/08aef918-94da-11e4-ad83-0e0c41326911/public_map

It is awaiting this pull request to merge before we serve all the components

https://github.com/CartoDB/cartodb/pull/2588

**Comment by namessanti** [comment]
added to https://github.com/CartoDB/docs/blob/new-items/external-tools.md

**Comment by javisantana** [comment]
oembed api doc should be part of the editor api which includes oembed, viz.json, static images and so on

**Comment by andrewxhill** [comment]
ah, oh, uh no no, i don't think so. 

this is more for people that build content tools that could support cartodb through oembed. people like wordpress, that can enable cartodb

**Comment by javisantana** [comment]
haha I don't actually mind, I do prefer not to publish oembed endpoint but it totally makes sense to publish with the rest of the public endpoints for visualization
