### ISSUE TITLE
Add three new sections to the Documentation

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#219]
To here,

![screen shot 2015-04-20 at 12 44 46 pm](https://cloud.githubusercontent.com/assets/370259/7235267/13809bde-e75b-11e4-9b73-96d5ea1fdb00.png)

1. Introduction (Jatorre's contributed introduction)
2. CartoDB Editor
3. CartoDB Platform
4. Data & Services (e.g. Twitter, Mailchimp, etc)
5. External tools (e.g. Cesium, Fiware, etc)

Can we add those sections so we can start flushing this out?

cc @matallo @saleiva ?

**Comment by matallo** [comment]
yeah, you can add them right away:

https://github.com/CartoDB/docs/blob/master/_layouts/index.html#L16

**Comment by andrewxhill** [comment]
okay, added but lots of work todo

https://github.com/CartoDB/docs/tree/new-items
