### ISSUE TITLE
create a search box on the docs page

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/docs#220]
Whenever I see this I try to select and type in it as if it were a searchbox. @pramsey requested it too

Could we change it into a search box so users can find content on how to use cartodb better?

![screen shot 2015-04-21 at 13 06 34](https://cloud.githubusercontent.com/assets/1041056/7258015/c8a54b32-e827-11e4-852d-d32724046adb.png)

**Comment by csobier** [comment]
Dup #279
