### ISSUE TITLE
Update CartoDB Multiuser docs

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#226]
http://docs.cartodb.com/cartodb-editor.html#cartodb-enterprise

**Comment by iriberri** [comment]
@andrewxhill could we push on this? we lots of resources in docs are very very very outdated http://docs.cartodb.com/faqs.html#what-does-the-removable-brand-feature-mean

**Comment by andrewxhill** [comment]
yeah, it is a good idea

**Comment by iriberri** [comment]
By the way, it could be great to fake the data (username, org name...) with
the web inspector for the screenshots (that will be less time consuming
that building a new org) so that we put standard information and not things
like Alvaro's account or BBVA information :-)


On Tuesday, May 26, 2015, Andrew W. Hill <notifications@github.com> wrote:

> yeah, it is a good idea
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/226#issuecomment-105654448>.
>


-- 

Carla Iriberri
*CartoDB*

**Comment by andrewxhill** [comment]
Well... we should have a fake multiuser account for creating these anyway
(and testing new things). Populated with fake names (sally, bob, and other
other classic name fillers)

On Tue, May 26, 2015 at 4:33 PM, Carla <notifications@github.com> wrote:

> By the way, it could be great to fake the data (username, org name...) with
> the web inspector for the screenshots (that will be less time consuming
> that building a new org) so that we put standard information and not things
> like Alvaro's account or BBVA information :-)
>
>
> On Tuesday, May 26, 2015, Andrew W. Hill <notifications@github.com> wrote:
>
> > yeah, it is a good idea
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CartoDB/docs/issues/226#issuecomment-105654448>.
> >
>
>
> --
>
> Carla Iriberri
> *CartoDB*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/226#issuecomment-105656891>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by iriberri** [comment]
Agree :+1:, that was a time saving attempt :)

On Tuesday, May 26, 2015, Andrew W. Hill <notifications@github.com> wrote:

> Well... we should have a fake multiuser account for creating these anyway
> (and testing new things). Populated with fake names (sally, bob, and other
> other classic name fillers)
>
> On Tue, May 26, 2015 at 4:33 PM, Carla <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > By the way, it could be great to fake the data (username, org name...)
> with
> > the web inspector for the screenshots (that will be less time consuming
> > that building a new org) so that we put standard information and not
> things
> > like Alvaro's account or BBVA information :-)
> >
> >
> > On Tuesday, May 26, 2015, Andrew W. Hill <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > yeah, it is a good idea
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/CartoDB/docs/issues/226#issuecomment-105654448>.
> > >
> >
> >
> > --
> >
> > Carla Iriberri
> > *CartoDB*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CartoDB/docs/issues/226#issuecomment-105656891>.
> >
>
>
>
> --
>
> andrewxhill <http://twitter.com/andrewxhill>
> http://cartodb.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/226#issuecomment-105658589>.
>


-- 

Carla Iriberri
*CartoDB*

**Comment by andrewxhill** [comment]
@namessanti bump

**Comment by namessanti** [comment]
https://github.com/CartoDB/docs/pull/251
