### ISSUE TITLE
Document in a FAQ: heatmaps not working in IE9

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#229]
Technical reason:

Heatmaps need that the browser supports cross domain requests in images in order to work, but IE9 just supports cross domain requests in documents, not in images.

From IE10 they work :)

**Comment by ztephm** [comment]
Hi @iriberri pull request is here: https://github.com/CartoDB/docs/pull/230

...sorry, didn't know how to make pull request appear here.
