### ISSUE TITLE
Check table layout in new Platform page

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#239]
Hey @matallo can you peak at the markdown table I used in the intro? 

https://docs.google.com/document/d/1ZL7Vq_BQvUi6qHLfOkN1OEifQOaDCwtLMVd4_GMhN1M/edit#

it is borked :|

**Comment by matallo** [comment]
kinda replicated 

![screen shot 2015-05-20 at 19 06 13](https://cloud.githubusercontent.com/assets/36676/7731847/a710355a-ff23-11e4-91b8-7291b8cca4da.png)
