### ISSUE TITLE
Add new data services

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#241]
Hey @miguelarias could you have someone start poking some of these in,

https://github.com/CartoDB/docs/blob/new-items/data-services.md

**Comment by miguelarias** [comment]
Yes, please @erodespons could you fill in the info we provide from a sales perspective for the data services listed in that page. And then @hboiten could you review, and ping me if my input is needed. The idea is to clarifiy which data services we offer in the platform, and how. And also add the new ones in the future.

**Comment by erodespons** [comment]
Started updating @miguelarias @hboiten. Difference between Free geocoding and Street Address Geocoding @andrewxhill ?

**Comment by andrewxhill** [comment]
Street level precision... all the others are city level precision and above

On Fri, Jun 12, 2015 at 10:12 AM, Eduardo Rodés Pons <
notifications@github.com> wrote:

> Started updating @miguelarias <https://github.com/miguelarias> @hboiten
> <https://github.com/hboiten>. Difference between Free geocoding and
> Street Address Geocoding @andrewxhill <https://github.com/andrewxhill> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/241#issuecomment-111560811>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by erodespons** [comment]
Updated!

Shall I include Mailchimp, Instagram, Google Drive, etc. there @andrewxhill ?

**Comment by andrewxhill** [comment]
yep, that'd be great!!

On Mon, Jun 15, 2015 at 4:26 PM, Eduardo Rodés Pons <
notifications@github.com> wrote:

> Updated!
>
> Shall I include Mailchimp, Instagram, Google Drive, etc. there
> @andrewxhill <https://github.com/andrewxhill> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/241#issuecomment-112108428>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by csobier** [comment]
I am not sure where this content came from (also related to the *new-items* branch?) I am worried about this content being merged with the Doc changes/format that I have already applied.  Let me know how I can help?
- I have described the available external data services in the CartoDB Editor / [Connect a Dataset](http://docs.cartodb.com/cartodb-editor.html#connect-dataset) procedure
- Let me know if this is a documentation requirement specific to the CartoDB platform doc?

**Comment by erodespons** [comment]
@andrewxhill ?

**Comment by matallo** [comment]
also, take into account we may be already communicating some of this here, if any it should be more dev oriented https://cartodb.com/data

**Comment by andrewxhill** [comment]
actually, this is quite old now. since then @vhamer worked on that data landing page. i'd rather drop this and think of just simple ways to supplement the work in /data.

**Comment by csobier** [comment]
Okay, sounds good to me.  I am closing this issue in the Docs repo.
If this data page requires content changes, that is a different repo (the [website](https://github.com/CartoDB/website) repo).
