### ISSUE TITLE
Update WMS section w/ info of limited projections support

### ISSUE THREAD

**Issue by viddo** [CartoDB/docs#243]
As part of https://github.com/CartoDB/cartodb/pull/3731 ([new modals](https://github.com/CartoDB/cartodb-management/wiki/new-editor#1-modals) project) to add a custom basemap, we now link to the docs for further info regarding why a WMS/WMTS URL is not considered valid:
![screen shot 2015-05-21 at 19 13 20](https://cloud.githubusercontent.com/assets/978461/7754519/8a8dbaf4-ffed-11e4-89df-b05c5bae2e89.png)

However, in the docs there is no info regarding this, but I found [a reply in the google group](https://groups.google.com/forum/#!msg/cartodb/yf81f1b_2m4/acnOnlozJBUJ):
> Currently, we're only supporting WMS files that contain data that uses a EPSG:3857 or EPSG:900913 coordinates, ...

We should add this info to the docs too, so the user knows what's up.

**Comment by matallo** [comment]
maybe worth linking to the blog? specifically that is being covered there http://blog.cartodb.com/wms-support/
