### ISSUE TITLE
Review faqs

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#244]
* Remove all mentions to visualizations/tables (unless we're actually referring to tables in a database/SQL sense)
* Update screenshots from old versions (including those who show redesigned parts or even the ones which show the Nokia day basemap: we can use positron instead)
* Check that we're not talking about non-existent features or ignoring features that exist at the moment

@andrewxhill

**Comment by andrewxhill** [comment]
assigning to brittany

**Comment by andrewxhill** [comment]
for parts of this you do not know, please grab santiago for help

**Comment by iriberri** [comment]
By the way, it could be great to fake the data (username, org name...) with
the web inspector for the screenshots (that will be less time consuming
that building a new org) so that we put standard information and not things
like Alvaro's account or BBVA information :-)

On Tuesday, May 26, 2015, Andrew W. Hill <notifications@github.com> wrote:

> for parts of this you do not know, please grab santiago for help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/244#issuecomment-105655723>.
>


-- 

Carla Iriberri
*CartoDB*

**Comment by iriberri** [comment]
Oh, this was for the enterprise documentstion issue. Sorry, wrote from the
phone :(

On Tuesday, May 26, 2015, Carla Iriberri <carla@cartodb.com> wrote:

> By the way, it could be great to fake the data (username, org
> name...) with the web inspector for the screenshots (that will be less time
> consuming that building a new org) so that we put standard information and
> not things like Alvaro's account or BBVA information :-)
>
> On Tuesday, May 26, 2015, Andrew W. Hill <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> for parts of this you do not know, please grab santiago for help
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CartoDB/docs/issues/244#issuecomment-105655723>.
>>
>
>
> --
>
> Carla Iriberri
> *CartoDB*
>
>

-- 

Carla Iriberri
*CartoDB*

**Comment by andrewxhill** [comment]
@brittanymicek bump

**Comment by brittanymicek** [comment]
See #252 @andrewxhill @iriberri thanks!
