### ISSUE TITLE
Update Shapefile Import docs with file-geodatabase info

### ISSUE THREAD

**Issue by ztephm** [CartoDB/docs#245]
@ztephm update this with info about file-geodatabase shapefiles according to this S/B ticket: 5467978

cc @iriberri

**Comment by iriberri** [comment]
:+1: 

Multi-file imports is something that is being discussed in several GitHub issues, so atm the workaround is splitting into independent ones.

**Comment by ztephm** [comment]
updated: https://github.com/CartoDB/docs/pull/249

**Comment by iriberri** [comment]
:+1:
