### ISSUE TITLE
typo in the Named Maps tutorial

### ISSUE THREAD

**Issue by imakihi** [CartoDB/docs#247]
I just found that "FROM" keyword is missing in the sql statement in the config.json example.

"sql": "select * named_map_tutorial_table",

should be 

"sql": "select * from named_map_tutorial_table",

I just copied and pasted the config.json example and couldn't figure out why the named map layer did not come through...

Thanks!

**Comment by ohasselblad** [comment]
thanks for reporting! fixed :+1:
