### ISSUE TITLE
Update removable brand FAQ

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#255]
http://docs.cartodb.com/faqs.html#what-does-the-removable-brand-feature-mean

The screenshot is super old!

Notice that this naming comes from the pricing so it's important to keep it:
![image](https://cloud.githubusercontent.com/assets/1730320/8410115/7e3147fa-1e7c-11e5-9a2c-c8c35954d07e.png)

**Comment by csobier** [comment]
Closing, I updated the removable brand question in PR #337.
