### ISSUE TITLE
Remove tables quota FAQ

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#257]
http://docs.cartodb.com/faqs.html#what-does-the-table-quota-mean-for-the-different-plans

We no longer limit tables per plans, so I'd remove this completely

**Comment by csobier** [comment]
Assigning to myself to remove this question from the FAQ section of the Docs portal.

**Comment by iriberri** [comment]
:+1:

**Comment by csobier** [comment]
Question removed from FAQ section of the Docs portal, closing issue.
