### ISSUE TITLE
Edit spelling of "visualisation" to Standard English 

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#272]
Minor doc edit for Standard English consistency. 

- From the example page, [Real Estate, Living Cities](https://cartodb.com/case-studies/living-cities/) / Solutions section

- Update "visualisations" to "visualization", as per the Stylish Writing Guide.

![example of standard english_visualization](https://cloud.githubusercontent.com/assets/13319925/8749551/3e06c874-2c70-11e5-9e3f-6e767a79c591.png)

**Comment by csobier** [comment]
Just practicing creating issues and playing around with markup hyperlinks in GitHub :-)
@brittanymicek @andrewxhill

**Comment by andrewxhill** [comment]
woot!

On Fri, Jul 17, 2015 at 10:43 AM, csobier <notifications@github.com> wrote:

> Just practicing creating issues and playing around with markup hyperlinks
> in GitHub :-)
> @brittanymicek <https://github.com/brittanymicek> @andrewxhill
> <https://github.com/andrewxhill>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/272#issuecomment-122297658>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by brittanymicek** [comment]
Nice catch! Good job!

On Fri, Jul 17, 2015 at 10:45 AM, Andrew W. Hill <notifications@github.com>
wrote:

> woot!
>
> On Fri, Jul 17, 2015 at 10:43 AM, csobier <notifications@github.com>
> wrote:
>
> > Just practicing creating issues and playing around with markup hyperlinks
> > in GitHub :-)
> > @brittanymicek <https://github.com/brittanymicek> @andrewxhill
> > <https://github.com/andrewxhill>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CartoDB/docs/issues/272#issuecomment-122297658>.
> >
>
>
>
> --
>
> andrewxhill <http://twitter.com/andrewxhill>
> http://cartodb.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/272#issuecomment-122297959>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by csobier** [comment]
Spelling updated and merged.  Confirmed on live Docs portal, closing issue.

https://github.com/CartoDB/website/commit/c03ce49ea1e27f6bbf9cfc0e260563dcc54be8b8
