### ISSUE TITLE
Update screenshots for new modals

### ISSUE THREAD

**Issue by viddo** [CartoDB/docs#277]
The screenshots for modals as seen on http://docs.cartodb.com/ are now outdated, so would need to be updated to reflect the [new modals](https://github.com/CartoDB/cartodb-management/wiki/New-Editor#1-modals), that was released on July 23rd.

[cartodb-editor.md](https://github.com/CartoDB/docs/blob/master/cartodb-editor.md):
- [x] http://docs.cartodb.com/cartodb-editor.html#dataset-privacy-settings (dataset_privacy branch-waiting to submit pull request until other branches are merged)
- [x] http://docs.cartodb.com/cartodb-editor.html#map-privacy-options (map_privacy branch- waiting to to submit pull request until other branches are merged- I also need to edit and reference a shared step from an earlier branch)
- [x] http://docs.cartodb.com/cartodb-editor.html#map-metadata (branch #289)
- [x] http://docs.cartodb.com/cartodb-editor.html#export-image ([pending PR](https://github.com/CartoDB/cartodb/pull/4658) at the time of writing this list) (branch #290)
- [x] http://docs.cartodb.com/cartodb-editor.html#including-an-external-basemap (branch #291)
- [x] http://docs.cartodb.com/cartodb-editor.html#share-your-map (branch #285)
- [x] http://docs.cartodb.com/cartodb-editor.html#geocoding-data (branch #306)
- [x] http://docs.cartodb.com/cartodb-editor.html#datasets-general-and-team-privacy-settings (branch #314)
- [x] http://docs.cartodb.com/cartodb-editor.html#maps-general-and-team-privacy-settings (branch #314)
- [x] http://docs.cartodb.com/cartodb-editor.html#about-the-twitter-datasource (branch #288)

[faqs.md](https://github.com/CartoDB/docs/blob/master/faqs.md):
- [x] http://docs.cartodb.com/faqs.html#how-can-i-export-my-data-from-cartodb (branch #285)
- [x] http://docs.cartodb.com/faqs.html#how-do-i-embed-a-map-in-my-siteblog (branch #285)

**Comment by csobier** [comment]
I spoke to Carla about this and I am assigning to myself.  These images in the Doc portal need to be updated.  Please include me in the production release cycle for any UI changes going forward. Thanks!

**Comment by viddo** [comment]
Ok, great! :+1:

**Comment by csobier** [comment]
@viddo , I have edited all of the sections above. I have also changed some images not included on this list.  And I am sure I will find other out of date windows along the way.... Since these specific tasks are complete, I am marking this issue as closed.

Thanks!

**Comment by csobier** [comment]
@viddo , I have edited all of the sections above. I have also changed some images not included on this list.  And I am sure I will find other out of date windows along the way.... Since these specific tasks are complete, I am marking this issue as closed.

Thanks!

**Comment by viddo** [comment]
Awesome, thanks to you! :dancer:
