### ISSUE TITLE
XML named as supported data file type, but seems not to be the case

### ISSUE THREAD

**Issue by tillnagel** [CartoDB/docs#287]
In http://docs.cartodb.com/cartodb-editor.html ([source](https://github.com/CartoDB/docs/blob/master/cartodb-editor.md)) the first section ("One Minute Intro") states CartoDB "accepts data in different formats (Excel, CSV, XML, SHP, GeoJSON [...]", yet XML doesn't work.

It is correct under [Supported File Formats](http://docs.cartodb.com/cartodb-editor.html#supported-file-formats) where XML is not mentioned.

**Comment by csobier** [comment]
Closing, updated in PR# 331.
