### ISSUE TITLE
Add more column merge information into merging datasets tutorial

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#322]
http://docs.cartodb.com/tutorials/merging_data.html

The details of this one are pretty focused on the spatial join. Could we improve it to cover a little bit more about the column join? Like what does mean to select some columns and not others, or what different selectors mean.

**Comment by yasharora73** [comment]
We could also have two datasets in the library to show how the column merge works, the same way we have it for spatial merge (world borders+populated places)

**Comment by matallo** [comment]
we should start moving these to academy

**Comment by csobier** [comment]
Closing issue in Docs and added to Academy repo.

**Note**: I've assigned a new issue #390 to myself to update the [Merging Datasets](http://docs.cartodb.com/cartodb-editor.html#merging-data) doc in the CartoDB Editor.
