### ISSUE TITLE
Update "Contact Sales" to  "Contact Solutions"

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#323]
Javi mentioned that the Sales team is being rebranded as the Solutions team.  There are several references in the documentation that mention contacting Sales for more information

Once the "Solutions" team has a working email contact address, update all references.

**Comment by csobier** [comment]
As per Dani, solutions@cartodb.com

**Comment by danicarrion** [comment]
This would be a reasonable approach, IMHO:

solutions-internal -> sales-engineering@cartodb.com
solutions-priv -> sales-engineers@cartodb.com
solutions -> sales@cartodb.com

**Comment by danicarrion** [comment]
And sorry @sdankas for messing up with the lists again :-)

BTW Sally, I've noticed a typo in my previous email about this (missing "s" in solutions-priv)

**Comment by danicarrion** [comment]
@csobier I think we can make the new solutions@cartodb.com point directly to the external sales mailing lists, as I bet 99% of the emails there will be related to enabling connectors, upsells, etc., that are managed by sales directly (typically Yash)

**Comment by danicarrion** [comment]
(we're still discussing this, don't do anything yet, please)

**Comment by hboiten** [comment]
Hi all: just to be clear... We should NOT replace ALL mentions of Sales with Solutions, please see clarification from JaTorre below
<img width="576" alt="screen shot 2015-08-26 at 16 51 49" src="https://cloud.githubusercontent.com/assets/11716425/9498663/d475ab10-4c12-11e5-8275-34bbe27f8245.png">
<img width="583" alt="screen shot 2015-08-26 at 16 51 59" src="https://cloud.githubusercontent.com/assets/11716425/9498669/ddf88310-4c12-11e5-8397-1ed64e84fd5a.png">

**Comment by csobier** [comment]
Closing issue without making changes. This is not a requirement in the Docs portal. I am leaving all references to 'Contact Sales' as is.
