### ISSUE TITLE
Update references to created_at and updated_at columns

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#333]
which will be no longer created by default: https://github.com/CartoDB/cartodb-postgresql/blob/4fe85a6a76650aadef117d4c4865e3ff7faee4ad/NEWS.md#090-2015-08-19

**Comment by csobier** [comment]
@iriberri , can I get more information about what the documentation requirements are for this issue?

**Comment by iriberri** [comment]
We might be mentioning `created_at` and `updated_at` columns in the docs. Since some weeks ago, when you import a table to CartoDB these timestamp columns are no longer created automatically.

Probably is just a matter of removing some mentions to them if they exist. In case it is said somewhere that "these columns are created blablabla", this would no longer happen. :-)

One appearing in the example: http://docs.cartodb.com/cartodb-platform/sql-api.html#response-formats

It would be enough to remove the lines:
````
 created_at: "2012-02-06T22:50:35.778Z",
      updated_at: "2012-02-12T21:34:08.193Z",
````

The same in the example that appears just below.

Several mentions here too: http://docs.cartodb.com/tips-and-tricks.html#date

**Comment by csobier** [comment]
There are a lot of syntax examples and some actual mentions of them in the
Import API and Maps API doc.  What is the suggested strategy?  Remove them
or add notes?

For example:
http://docs.cartodb.com/cartodb-platform/import-api.html#sync-tables
http://docs.cartodb.com/cartodb-platform/import-api.html#params-4
http://docs.cartodb.com/cartodb-platform/import-api.html#response-9
http://docs.cartodb.com/cartodb-platform/import-api.html#example-8


Maps API:
http://docs.cartodb.com/cartodb-platform/maps-api.html#response

SQL API:
http://docs.cartodb.com/cartodb-platform/sql-api.html#response-formats


On Fri, Oct 2, 2015 at 6:09 AM, Carla <notifications@github.com> wrote:

> We might be mentioning created_at and updated_at columns in the docs.
> Since some weeks ago, when you import a table to CartoDB these timestamp
> columns are no longer created automatically.
>
> Probably is just a matter of removing some mentions to them if they exist.
> In case it is said somewhere that "these columns are created blablabla",
> this would no longer happen. :-)
>
> One appearing in the example:
> http://docs.cartodb.com/cartodb-platform/sql-api.html#response-formats
>
> It would be enough to remove the lines:
>
>  created_at: "2012-02-06T22:50:35.778Z",
>       updated_at: "2012-02-12T21:34:08.193Z",
>
> The same in the example that appears just below.
>
> Several mentions here too:
> http://docs.cartodb.com/tips-and-tricks.html#date
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/333#issuecomment-144981529>.
>



-- 
*Christa Sobier*
Technical Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, Brooklyn, New York, 11211, USA
T: +1.917.463.3232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by iriberri** [comment]
http://docs.cartodb.com/cartodb-platform/import-api.html#sync-tables
http://docs.cartodb.com/cartodb-platform/import-api.html#params-4
http://docs.cartodb.com/cartodb-platform/import-api.html#response-9
http://docs.cartodb.com/cartodb-platform/import-api.html#example-8

These ones are ok. They don't refer to the updated_at and created_at columns, but to the metadata of the created tables.

http://docs.cartodb.com/cartodb-platform/maps-api.html#response

Same here, this is just the updated_at parameter of the named maps, not any column, although they share the name :-)

http://docs.cartodb.com/cartodb-platform/sql-api.html#response-formats

These ones *are* the ones we're looking for, which are the ones I pasted above. We can just remove those two lines, or if they're just examples we can just forget about it if there's no writing about them, but perhaps it could be confusing to keep their appearance in the documentation when we don't create them anymore. What do you think?

If you haven't found more matches, then I think there's nothing really critical that we are missing to edit with respect to these old columns :-)

**Comment by csobier** [comment]
Excellent, thanks Carla! I'm just identifying a list of areas that require doc updates:

 - [ ] SQL API, **remove these lines from the response formats section**
http://docs.cartodb.com/cartodb-platform/sql-api.html#response-formats

`created_at: "2012-02-06T22:50:35.778Z",`
     ` updated_at: "2012-02-12T21:34:08.193Z",`


- [ ] Tips & Tricks, **Replace this section**
http://docs.cartodb.com/tips-and-tricks.html#date
And update with the new timestamp function that Carla describes here: https://github.com/CartoDB/support/issues/5

**Comment by iriberri** [comment]
Thanks :revolving_hearts:
