### ISSUE TITLE
Note about torque layers and ambiguous column name

### ISSUE THREAD

**Issue by jsanz** [CartoDB/docs#334]
When creating a torque with categories layer, the sql that defines the data can't have a column named `torque_cotegory` because it drives to an weaird error not easy to determine by the final user. So I'd add a note at [torque section](http://docs.cartodb.com/cartodb-editor.html#torque) on the editor documentation but wasn't sure where exactly and with which form (a **Tip** maybe?).

**Comment by csobier** [comment]
Excellent, great information.  Note that I need to rewrite the entire Map Wizards content (# 332) but for now, does this note suffice in the [Torque Category](http://docs.cartodb.com/cartodb-editor.html#torque-category) section?  (*I am not sure what the error message is. Please let me know if the note below is too vague or if there is more information I should know?*)

**Note:** If you select Torque Category as the map type and apply a custom [SQL query](http://docs.cartodb.com/cartodb-editor.html#custom-sql), avoid using `torque_category` as a column name to prevent errors.

**Comment by jsanz** [comment]
To cover better all the cases I'd change a bit the text because it would happen not only with custom queries but also with any table if `torque_category` is one of the column names.

**Note:** If you select Torque Category as the map type, ensure your SQL query is not using `torque_category` as a column name to prevent errors.

**Comment by csobier** [comment]
Okay, how about this?  If you sign-off, I'll post live.

**Note:** If you select Torque Category as the map type, ensure your SQL query is not using `torque_category` as a column name to prevent unexpected behaviors.

**Comment by jsanz** [comment]
:+1:
