### ISSUE TITLE
table header is not styled

### ISSUE THREAD

**Issue by matallo** [CartoDB/docs#342]
<img width="739" alt="screen shot 2015-09-03 at 15 37 35" src="https://cloud.githubusercontent.com/assets/36676/9659645/cfde0c7e-5251-11e5-8e94-9ef78b046850.png">

**Comment by piensaenpixel** [comment]
We know.. but thanks :)

**Comment by matallo** [comment]
just for not losing track, didn't assign anybody nor a milestone

**Comment by piensaenpixel** [comment]
i'm assing myself dont worry
