### ISSUE TITLE
Static image, cartodb.js section, getURL should be getUrl

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#343]
In all cases

http://docs.cartodb.com/cartodb-platform/cartodb-js.html#static-maps

**Comment by csobier** [comment]
@andrewxhill Is this strictly a case sensitivity fix?

Image.**getUrl**(callback(err, url))

Gets the URL for the image requested.

Image.**getUrl**
```<script>
cartodb.Image(vizjson_url)
  .size(600, 400)
  **.getUrl**(function(err, url) {
      console.log('image url',url);
  })
</script>
```

**Comment by andrewxhill** [comment]
yep, case sensitive

**Comment by jsanz** [comment]
Fixed on this [PR](https://github.com/CartoDB/cartodb.js/pull/656)
