### ISSUE TITLE
Supported formats "notes" don't have a referenced explanation in the text

### ISSUE THREAD

**Issue by iriberri** [CartoDB/docs#355]
![image](https://cloud.githubusercontent.com/assets/1730320/9792348/fbe0208a-57df-11e5-8643-2c561cc2de44.png)

The asterisks in the formats do not have an explanation in the text below.

For example:

* CSV format blablabla
** Shapefile format blablabla

It seems that the asterisk for Shapefile, for example, is being treated as Markdown italics letters. The whole text below the section is in italics: 

![image](https://cloud.githubusercontent.com/assets/1730320/9792418/499c222e-57e0-11e5-951e-624e0ba20b8c.png)

**Comment by csobier** [comment]
Merged in PR#364.
