### ISSUE TITLE
Update Edit menu options and Dashboard view options

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#363]
Product updated the Edit menu options and the dashboard menu options.  All doc images and procedures need to be updated to reflect these changes (Change are already live so we will not be in sync. Sigh. I'm assigning to the next milestone.
- [Product issue #5178](https://github.com/CartoDB/cartodb/issues/5178#event-408386527)
- [Product issue #5487](https://github.com/CartoDB/cartodb/pull/5487#event-408386528)

**Comment by matallo** [comment]
we'll totally have to rethink and streamline the process so all these images are in sync, don't worry, we'll tackle that soon and sorry for the current inconvenience :(

**Comment by csobier** [comment]
It's okay, happy to help improve the workflow :-)  (So far, I am manually copying the Product milestones to the Docs repo but there must be a way to automate this process so that there is more transparency). I will have this issues closed by the assigned Doc milestone.

**Comment by csobier** [comment]
Changes merged with PR #373
