### ISSUE TITLE
Remove mentions of Oauth support in SQL API and other docs locations

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/docs#368]
cc @javisantana @CartoDB/solutions 

Apparently we don't actually support Oauth, we support XAuth, and it's only a partial support at that. We should remove our mentions of OAuth from the docs until we actually support it.

http://docs.cartodb.com/cartodb-platform/sql-api.html#oauth

**Comment by csobier** [comment]
Tagging @MariaCheca, stayed tuned to this issue and let me know if this will affect the Account options (OAuth credentials)?

**Comment by danicarrion** [comment]
actually, if we don't support xAuth, we could even hide the client/secret pair from user settings in the editor? // @javisantana

**Comment by javisantana** [comment]
For me we should remove everything related to oauth until we ensure it works and have the pretty basic funcionallity

**Comment by danicarrion** [comment]
ok, the only problem I see, now that I think about it, is that there _may_ be people already using it

**Comment by andrewbt** [comment]
I know for a fact Cloudsherpas is, or at least they have tested solutions
with it (and are assuming it is "3-legged Oauth" and not "Xauth") They keep
wishing we had 2-legged Oauth, actually

On Wed, Sep 16, 2015 at 2:44 PM, Dani Carrión <notifications@github.com>
wrote:

> ok, the only problem I see, now that I think about it, is that there *may*
> be people already using it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/368#issuecomment-140730620>.
>



-- 
Andrew Thompson, Solutions Engineer

*CartoDB* | 143 Roebling St, 2A, Brooklyn, NY 11211
athompson@cartodb.com | T +1 508.333.7265 <+15083337265>
Web cartodb.com | Twitter @cartodb <http://twitter.com/cartodb>
Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by danicarrion** [comment]
ok, so let's just wipe it away from the docs, then

**Comment by csobier** [comment]
Okay, so the requirement is to remove all mention of OAuth credentials from the doc. This will effect SQL API doc, CartoDB Editor doc, and FAQ's.  

I will assign to myself and update the doc once Product removes the [related feature](https://github.com/CartoDB/cartodb/issues/5552) (no milestone).
