### ISSUE TITLE
Add list of weights that can be applied to font families w/CartoCSS

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#382]
The CartoDB Editor currently supports the following [fonts](http://docs.cartodb.com/cartodb-editor.html#supported-fonts) through the wizard. The requirement is to document the supported weight formats that can be applied to these font families through CartoCSS.

As per @makella , you can use each weight from each supported family through cartocss. So even though in the wizard the only option for DejaVu Sans is Book, you can use other weights from the family ex: `text-face-name: 'DejaVu Sans Oblique’;`

*Related to platform issue [#1123](https://github.com/CartoDB/cartodb-platform/issues/1123)

*Note:* CartoCSS doc is being implemented in phases, as we continue to enhance the docs. I will assign a milestone for this issue after the first phase of CartoCSS content is released.

**Comment by makella** [comment]
These should get better and we shouldn't recommend the use of all fonts on maps (ex: Lato Hairline), but here is a visual list of what's supported right now (minus unifont Medium which I can't find):
![visual-fonts](https://cloud.githubusercontent.com/assets/1566273/10085139/8c5a1172-62c4-11e5-92ae-996b743cf440.jpg)
Also referenced here: https://github.com/CartoDB/cartodb-platform/issues/1123

**Comment by csobier** [comment]
I updated the Supported Fonts formats in PR #388.  I still need to include a snapshot of each of these fonts as a future enhancements (once we get confirmation about all the supported fonts).

**Comment by csobier** [comment]
Mamata updated this list!!!  Thanks Mamata!
![visual-fonts](https://cloud.githubusercontent.com/assets/1566273/10250826/00d2cf62-68e2-11e5-9658-76c7b95dee61.jpg)

I updated the supported fonts accordingly and published with PR #420.
