### ISSUE TITLE
Add shield-wrap-character `string` example- CartoCSS

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#385]
We need our own CartoDB example for this parameter.  @makella to the rescue!

##### shield-wrap-character `string`

------------ | -------------
Description | Enables you to wrap text with a character, rather than with a space. This is especially useful for long text names.
Sample CartoCSS Code | `shield-wrap-character: '_';`
Default Value | `undefined
Available Values | See [string](#string).
Related Example | [Always break long city names (New Bedford Massachusetts) on two lines](https://www.mapbox.com/tilemill/docs/guides/styling-labels/#multi-line-labels) 
| - *NEED TO PROVIDE CARTODB EXAMPLES (links to blocks, public maps, etc.)

**Comment by makella** [comment]
![screen shot 2015-09-24 at 12 42 58 pm](https://cloud.githubusercontent.com/assets/1566273/10083064/f41d435c-62b9-11e5-95d7-236dab5f4a9c.png)

```
#highway_shield {
   shield-file: url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/mamataakella/assets/20150924175307shield2.png);
   shield-face-name: 'Open Sans Bold';
   shield-name: [type] + '_' + [number];
   shield-fill: #fff;
   shield-size: 25;
   shield-halo-fill: teal;
   shield-halo-radius: 2;
   shield-wrap-width: 1;
   shield-wrap-character: '_';
}
```

**Comment by csobier** [comment]
@makella , I need JB Fiddle examples to display the output and CartoCSS code.  Are you using a Public dataset? (So that I can recreated this)

**Comment by makella** [comment]
@csobier i made a fake dataset with a couple of points along a road and got a highway shield file and assigned the CartoCSS. I'll make a fiddle of the two and send them to you... likely later today.

**Comment by makella** [comment]
@csobier here you go:
http://cartodb.github.io/labs-cdbfiddle/#https://team.cartodb.com/u/mamataakella/api/v2/viz/f542f554-62e3-11e5-a7a2-0e0c41326911/viz.json

**Comment by csobier** [comment]
Fabulous, thank you!
