### ISSUE TITLE
Add  line-pattern-file `uri` example- CartoCSS

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#386]
We need our own CartoDB example for this parameter. (Thank you @makella!)  I will add your example to the docs.

##### line-pattern-file `uri`

Description | A defined image file that renders the pattern of a line. The image repeats along the line.
Sample CartoCSS Code | `line-pattern-file: ur(cliff.png);`
Default Value | none
Available Values | See [uri](#uri).
Related Examples | [Cliff lines](https://www.mapbox.com/tilemill/docs/guides/styling-lines/)
| WE NEED OUR OWN EXAMPLE HERE (public maps, blocks, blogs, etc.)

**Comment by csobier** [comment]
I am getting an unrecognized error message when applying the `line-pattern-uri` parameter, @ztephm confirmed that she is also getting an error. 

@rochoa @fdansv , Can you confirm if this parameter is supported (should work, keep in doc) of if this is a bug (report as product issue and remove from doc)?

**Comment by makella** [comment]
@csobier how are you writing it out in the editor? i was testing this last week and it was working for me

**Comment by makella** [comment]
it is working for me... this is an [ugly example](http://cdb.io/1MUojqO), but if you want to try:
```
#ne_10m_admin_1_states_provinces {
  line-pattern-file: url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/mamataakella/assets/20151005164516line-2.png);
}
```

**Comment by ztephm** [comment]
ah i was trying line-pattern-uri instead of line-pattern-file. Works for me using line-pattern-file.

**Comment by csobier** [comment]
Thanks for confirming Mamata. Would this JB Fiddle be okay to show, just for references purposes of a related example? 
http://cartodb.github.io/labs-cdbfiddle/#https://csobier.cartodb.com/api/v2/viz/3db9be82-360a-11e5-9c46-0e018d66dc29/viz.json

**Comment by makella** [comment]
no problem @csobier 
if its only for reference purposes and internal, sure... if that map will be viewed by anyone outside, let's get a better line pattern! :)

**Comment by csobier** [comment]
JB Fiddles are public, by design, so I would love a better line pattern if you've got one :-)

**Comment by makella** [comment]
ok, i'll have to make one and test it out... that was a test i was doing a couple of weeks ago and it isn't right so when i have a better example, i'll share that.  but let's not use that example if we can help it!

**Comment by makella** [comment]
@csobier let's use this example instead:
http://cartodb.github.io/labs-cdbfiddle/#https://team.cartodb.com/u/mamataakella/api/v2/viz/21560880-6dce-11e5-b0be-0ea31932ec1d/viz.json

looks better than the other ugly line pattern i had in the previous example!

**Comment by csobier** [comment]
You are my hero, lovin the Fiddles!  Thanks.

**Comment by makella** [comment]
:)
