### ISSUE TITLE
Add shield-halo-fill `color` example- CartoCSS

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#387]
We need our own CartoDB example for this parameter. (I will add the example that @makella provides to the docs)

##### shield-halo-fill `color`

------------ | -------------
Description | Specifies the color of the halo around the text.
Sample CartoCSS Code | `shield-halo-fill: #FFFFFF;`
Default Value | `#FFFFFF`, the halo color is white by default
Available Values | See [color](#color).
Related Example | [Design Control with Regular Expressions](https://www.mapbox.com/blog/design-control-with-regular-expressions-in-mapbox-studio/)
|	NEED TO ADD OUR OWN SIMILAR EXAMPLE INSTEAD (links to blocks, public maps, etc.)

**Comment by makella** [comment]
![screen shot 2015-09-24 at 12 38 49 pm](https://cloud.githubusercontent.com/assets/1566273/10082914/4f305532-62b9-11e5-9a26-5b87e91beca5.png)

```
#highway_shield {
  shield-file: url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/mamataakella/assets/20150924175307shield2.png);
  shield-face-name: 'Open Sans Bold';
  shield-name: [number];
  shield-fill: #fff;
  shield-size: 35;
  shield-halo-fill: teal;
  shield-halo-radius: 2;
}
```

**Comment by csobier** [comment]
@makella , I need JB Fiddle examples to display the output and CartoCSS code.  Are you using a Public dataset? (So that I can recreated this)

**Comment by makella** [comment]
@csobier 
here you go:
http://cartodb.github.io/labs-cdbfiddle/#https://team.cartodb.com/u/mamataakella/api/v2/viz/ddfc8a58-6dc5-11e5-8b99-0ea31932ec1d/viz.json

**Comment by csobier** [comment]
Thanks Mamata,  you rock!
