### ISSUE TITLE
Add `-torque-clear-color` to CartoCSS doc

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#394]
Related to CartoDB Management repo, [issue 4012](https://github.com/CartoDB/cartodb-management/issues/4012):

I have not seen -torque-clear-color in CartoDB? I need confirmation if this works and should be added to the doc?

**Comment by csobier** [comment]
TEST: 

 "-torque-clear-color": {
            "css": "-torque-clear-color",
            "type": "color",
            "default-value": "rgba(255, 255, 255, 0)",
            "default-meaning": "full clear",
            "doc": "color used to clear canvas on each frame"
        },

**Comment by ohasselblad** [comment]
`-torque-clear-color

**Comment by javisantana** [comment]
this is kind of a hack I added, could we leave as a undocumented-but-nice feature?

**Comment by ohasselblad** [comment]
what does it do/why is it nice?

**Comment by csobier** [comment]
I am closing this issue, as there is no requirement to document this.  We can always re-open this issue if we decide to publicly support this.

FYI @ohasselblad, I made rambo share a sample so we can see why it's so nice :-)

https://rambo-test.cartodb.com/viz/b9bed4da-86ca-11e4-989b-0e4fddd5de28/embed_map
