### ISSUE TITLE
better style tables

### ISSUE THREAD

**Issue by matallo** [CartoDB/docs#397]
current markup is ok, but the aspect is a bit messy

http://docs.cartodb.com/cartodb-editor.html#cartocss-properties

/cc @piensaenpixel @carlostallon @csobier

**Comment by csobier** [comment]
@matallo , same issue as #342

**Comment by matallo** [comment]
yeah, I'm leaving it anyway, former issue is only the headings and would be a bug

for this format to work we need to redesign a bit the tables IMO

**Comment by csobier** [comment]
I would love to be able to create custom style tables (just like using an editor!)  :-)  Any enhancements you can add to the markdown code would be an improvement.
