### ISSUE TITLE
`-torque-frame-count` CartoCSS property undefined?

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#410]
As per @ohasselblad comment:
http://docs.cartodb.com/cartodb-editor.html#torque-frame-count-number

Is the default value really undefined or does it depend on input data?

@rochoa @fdansv Please advise, so that we can ensure the doc is correct.

**Comment by rochoa** [comment]
Default value is 128, as per https://github.com/CartoDB/torque-reference/blob/bc22ced9c73ffda071893e90b7c955bf54de8cf0/1.0.0/reference.json#L39-L45

**Comment by rochoa** [comment]
But that value is set when parsing cartocss. OTOH windshaft imposes a default value of 64 when value is not set.

**Comment by csobier** [comment]
@rochoa Does this work if I include both values as part of the description?

##### -torque-frame-count `number`
--- | ---
Description | Specifies the number of animation steps/frames in your torque animation.
Sample CartoCSS Code | `-torque-frame-count:128;`
Default Value | 128, the data is broken into 128 time frames when parsing CartoCSS. If the data contains a fewer number of total frames, a lessor value is used.
| **Note:** A default value of 64 is applied if no default value is specified.
Available Values | See [numbers](#numbers).

**Tip:** This is the _Steps_ option from the [Torque wizard](cartodb-editor.html#torque).

**Comment by rochoa** [comment]
Sorry, I mislead you with my previous comment (I left a comment here for another issue). Default torque-frame-count is 128.

p.s.: The 64 value was related to buffer-size issue.

**Comment by csobier** [comment]
Ah, okay thanks.  Will leave 128 as default value, thanks for confirming.

**Comment by rochoa** [comment]
yw! :smile:
