### ISSUE TITLE
`-torque-animation-duration-number` CartoCSS value?

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#411]
As per @ohasselblad review of the CartoCSS doc:
http://docs.cartodb.com/cartodb-editor.html#torque-animation-duration-number

 0 indicates a large number, as in billions of seconds. fdansv knows

@fdansv , can you clarify so that I enhance the description and add more details?

**Comment by fdansv** [comment]
This attribute will accept any positive number value, with no known upper limit. The default value is undefined because it's a required rule.

**Comment by csobier** [comment]
Thanks!  I've slightly updated the definition of this parameter. Changes merged in PR #424
