### ISSUE TITLE
`buffer-size-float` CartoCSS default value?

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#412]
As per @makella comment on the CartoCSS doc:
http://docs.cartodb.com/cartodb-editor.html#buffer-size-float

check to make sure that buffer-size is default 0... i was talking with raul this morning and i thought he said the default is 64…

@rochoa , Please advise so that we can ensure the doc is correct.

**Comment by csobier** [comment]
@rochoa Please advise what the default value should be so we can ensure the doc is correct.

**Comment by rochoa** [comment]
There are two options for buffer-size: per [map buffer-size](https://github.com/CartoDB/mapnik-reference/blob/a9a4536116aa8b3e1fe6433b2c8da25321dc7f7d/2.3.0/reference.json#L349-L355) and [per layer buffer-size](https://github.com/CartoDB/mapnik-reference/blob/a9a4536116aa8b3e1fe6433b2c8da25321dc7f7d/2.3.0/reference.json#L163-L168).

As you can see in above linked reference, default value is set to 0 in both, but in our case we change the default value for the map buffer-size to 64. So 64 is applied to all layers but can be override with cartocss for both, map and layer.

HTH.
