### ISSUE TITLE
change 'point-file-uri` CartoCSS sample code

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#413]
@makella  , you suggested that the default sample code code be confusing.
http://docs.cartodb.com/cartodb-editor.html#point-file-uri

Can you provide me with an alternate example (and explanation) so that I can update the doc accordingly?

**Comment by makella** [comment]
@csobier sure.

in cartodb when you choose an image, you get an external url. the reference above makes it look like you can point to an image file on your local machine `url(images/image.png)` and use that in your map. an easy fix would be to put a generic url `point-file: url(http://www.image.com/image.png);` in the cartocss example.

**Comment by csobier** [comment]
Excellent, I will apply your example as the Sample CartoCSS code instead.  Thank you!

Additionally, I think it's worth noting in the URI value section of the doc, if this applies to all CartoCSS images in CartoDB.  http://docs.cartodb.com/cartodb-editor.html#uri
- Can you verify if the description (see link) is correct? (it suggest using quotes.  Is that correct?)  
- Would the following note be true?
**Note:** In CartoDB, images applied through CartoCSS cannot be selected from folders. You can define a resource of the image location with this URI value.

- [ ] I will also update any other CartoCSS property using the URI value, so this is consistent.

**Comment by csobier** [comment]
@makella , I updated all the code for URI parameters.  I just need confirmation about adding quotes? and if the note is correct?  

url('http://com.cartodb.users-assets.production.s3.amazonaws.com/patterns/diagonal_1px_med.png');`

**Comment by makella** [comment]
@csobier so you don't need the quotes... you can do something like this and it works fine:

```
#layername {
  marker-file: url(http://com.cartodb.users-assets.production.s3.amazonaws.com/pin-maps/pin10.svg);
}
```

**Comment by makella** [comment]
oh sorry this is for `point-file` so you can do:
```
#layername {
   point-file: url(http://com.cartodb.users-assets.production.s3.amazonaws.com/pin-maps/pin10.svg);
}
```

**Comment by csobier** [comment]
Thanks for confirming.  It works with and without quotes, I was just wondering why it was mentioned (I'm going to remove this statement).  I will apply all these notes and update URI examples.  Thank you!

**Comment by makella** [comment]
@csobier right... sure does!
and no problem!
