### ISSUE TITLE
Need to figure out how to show/format CartoCSS examples?

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#415]
The next phase of the CartoCSS doc update is to start including references of CartoCSS examples (for single properties, multi-style properties, and multi-layers).  
- Blockpages are ideal but there is not a consistent format.
- Also, I already have some public maps examples to reference, but I need to include the related CartoCSS syntax somehow.  I do not want to add a ton of code blocks to the CartoCSS Properties doc.  The related examples should only be links to more enhanced resources.

Tagging @andrewxhill for ideas, as this may relate to other situations where we need to reference examples from the website, blogs, etc.

**Comment by matallo** [comment]
@carlostallon write this down when designing new docs

**Comment by carlostallon** [comment]
roger

**Comment by csobier** [comment]
Since Mamata confirmed that CartoCSS is not supported on CartoDB Blocks, we are leaning toward encouraging people to create JS Fiddle examples that I can reference....

**Comment by csobier** [comment]
Closing issue, links to JB Fiddle examples are working out well.  Anyone can reopen this issue if they have any questions/comments.  Thanks!
