### ISSUE TITLE
Add (column_name) additions to CartoCSS -torque-aggregation-function

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#432]
Add (column_name) additions as an available [Torque Category](http://docs.cartodb.com/cartodb-editor.html#cartocss---torque-category-maps) value for the CartoCSS property `-torque-aggregation-function`

Info found in the ["More on the Torque unknown" blog](http://andrewxhill.com/blog/2015/04/17/torque-unknown/)

Specifically:
- Category maps that categorize
- Category maps that diverge

@andrewxhill , Category_name is the only value I found missing from the Torque CartoCSS content, let me know if anything else should be added?  
Also, if you are using a public dataset for the blog examples, I can create Fiddle examples to reference in the doc?  Otherwise, I can link to this blog as a reference.

**Comment by andrewxhill** [comment]
awesome!

On Wed, Oct 14, 2015 at 12:03 PM, csobier <notifications@github.com> wrote:

> Add (category_name) as an available Torque Category
> <http://docs.cartodb.com/cartodb-editor.html#cartocss---torque-category-maps>
> value for the CartoCSS property -torque-aggregation-function
>
> Info found in the "More on the Torque unknown" blog
> <http://andrewxhill.com/blog/2015/04/17/torque-unknown/>
>
> Specifically:
>
>    - Category maps that categorize
>    - Category maps that diverge
>
> @andrewxhill <https://github.com/andrewxhill> , Category_name is the only
> value I found missing from the Torque CartoCSS content, let me know if
> anything else should be added?
>
> Also, if you are using a public dataset for the blog examples, I can
> create Fiddle examples to reference in the doc? Otherwise, I can link to
> this blog as a reference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/issues/432>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by andrewxhill** [comment]
i don't think those were public data actually... so we might need to
recreate

On Wed, Oct 14, 2015 at 12:04 PM, Andrew Hill <andrewxhill@gmail.com> wrote:

> awesome!
>
> On Wed, Oct 14, 2015 at 12:03 PM, csobier <notifications@github.com>
> wrote:
>
>> Add (category_name) as an available Torque Category
>> <http://docs.cartodb.com/cartodb-editor.html#cartocss---torque-category-maps>
>> value for the CartoCSS property -torque-aggregation-function
>>
>> Info found in the "More on the Torque unknown" blog
>> <http://andrewxhill.com/blog/2015/04/17/torque-unknown/>
>>
>> Specifically:
>>
>>    - Category maps that categorize
>>    - Category maps that diverge
>>
>> @andrewxhill <https://github.com/andrewxhill> , Category_name is the
>> only value I found missing from the Torque CartoCSS content, let me know if
>> anything else should be added?
>>
>> Also, if you are using a public dataset for the blog examples, I can
>> create Fiddle examples to reference in the doc? Otherwise, I can link to
>> this blog as a reference.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CartoDB/docs/issues/432>.
>>
>
>
>
> --
>
> andrewxhill <http://twitter.com/andrewxhill>
> http://cartodb.com
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by andrewxhill** [comment]
Here is the dataset! https://team.cartodb.com/u/andrew/tables/twitter_burgerking_mcdonalds/public
