### ISSUE TITLE
[cartodb.js] extend getBounds description if needed

### ISSUE THREAD

**Issue by matallo** [CartoDB/docs#448]
in cartodb.js repo, removed from other_stuff

https://github.com/CartoDB/cartodb.js/commit/581dd968cfe4c5e24d23c23321d16326c17b7597

feel free to close this

**Comment by csobier** [comment]
@rochoa , please advise as to what to do (I do not know).  Should this content be added to the cartodb.js doc?  Let me know what the requirements are.
