### ISSUE TITLE
[cartodb.js] include old reference to docs

### ISSUE THREAD

**Issue by matallo** [CartoDB/docs#449]
- [x] `doc/raster_howto.md`
- [x] `doc/metrics.md`

feel free to close and remove if not needed anymore

**Comment by csobier** [comment]
@rochoa , please advise as to what to do (I do not know).  Should any of this content be added to the cartodb.js?  Let me know what the requirements are.

**Comment by matallo** [comment]
I'm removing the assignee and milestone, but will keep the issue open for tracking
