### ISSUE TITLE
[sql-api] include metrics in docs 

### ISSUE THREAD

**Issue by matallo** [CartoDB/docs#453]
- `doc/metrics.md` is not currently included in docs, but file exists in repo

/cc @rochoa

**Comment by rochoa** [comment]
I wouldn't include metrics in official documentation. It's about internal application metrics and end users cannot access those metrics.

**Comment by csobier** [comment]
@rochoa , please advise as to what to do (I do not know).  Should any of this content be added to the sql-api doc?  Let me know what the requirements are.

**Comment by rochoa** [comment]
As I said I would not include this documentation in the official documentation.
