### ISSUE TITLE
No documentation on adding points, lines, or polygons to a table

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#92]
both empty table 
or adding features to an existing dataset 
both are missing

**Comment by csobier** [comment]
@axh, I created a new procedure describing how to [Create an Empty Dataset](http://docs.cartodb.com/cartodb-editor.html#create-an-empty-dataset).  I also created the "[Add Feature](http://docs.cartodb.com/cartodb-editor.html#add-feature)" content and added to the docs, which describes this.

Let me know if there is a method to add points, lines, and polygons using the Data View (besides just adding new rows and columns)?  
Also, any rules or best practices about creating these type of coordinates is probably good to know and should be doc'd.  Please advise.

**Comment by andrewxhill** [comment]
nope, no way to do it really in the data view. for a point you could add a row and then enter the lat/lon in the_geom field, but it's a bit complicated

**Comment by csobier** [comment]
Okay, your call.  If you want to dump any details here, I'll translate it in end-user terms. Or, is this something that should be a future Academy lesson?

Otherwise, if the above content satisfies this doc requirement, you can close this issue.

**Comment by andrewxhill** [comment]
yeah, i think it is good for now and we can explore in later iterations of the table view making it easier
