### ISSUE TITLE
Document the new overlay properties toolbar

### ISSUE THREAD

**Issue by javierarce** [CartoDB/docs#94]
We need to document the new properties toolbar for the overlays.

Here's the things we've changed:

- We removed the dropdown and replaced it with the toolbar.
- Clicking on a text or image overlay makes a properties toolbar to appear (we also removed the 'edit' button that appeared when you hovered an overlay)
- Double-clicking on a text or image overlay allows to edit their content.
- The toolbar includes these actions: push an overlay to the front, pull tothe  back, clone it and remove it.

Ping me if you need help with this.

**Comment by namessanti** [comment]
https://github.com/CartoDB/docs/pull/200
